### ISSUE TITLE
youtube complaining keyframe <4 needed,

### ISSUE THREAD

**Issue by hostbbb** [lukas2511/bbb-streaming#1]
Great work Lukas...,  fired up no problem, wanted to be the first issue on you new project,

![image](https://user-images.githubusercontent.com/519542/110791907-c20bc080-8240-11eb-96de-3fdc52c5ac5d.png)

will look at code to see where this is set.

regards,
Stephen

**Comment by lukas2511** [comment]
Can you give it a try with aa4dd06d2810e7e3ff8ee9352054beb85beb0a43 (or the newset docker build)? It should be set down to 2 seconds now.

**Comment by hostbbb** [comment]
confirmed with youtube, working good,  1080p 5sec delay... and forcing youtube to HD client gives good quality.
