### ISSUE TITLE
sending bad !view command stopped future commands

### ISSUE THREAD

**Issue by hostbbb** [lukas2511/bbb-streaming#3]
bad command !view SBS hung main program, no more events processed.
![image](https://user-images.githubusercontent.com/519542/110837990-f054c480-826f-11eb-8d3a-9203d1e3684a.png)

**Comment by lukas2511** [comment]
Should be fixed. This is also something that's kinda temporary, going to set up a better command system with permission checks etc at some point. Generally there's a lot of error handling still to be implemented.
